---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mk-gen.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "mk-gen.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
